### ISSUE TITLE
请问您的联系方式是多少

### ISSUE THREAD

**Issue by Vibert2s** [yishellmeta/telegram-red-vue-manager#2]
Rt

**Comment by eBayMeta** [comment]
亿贝团队专注于区块链金融、即时通讯等行业的软件服务。核心技术人员有着10年+的区块链行业技术经验。我们的软件服务包含：

🍬【   DAPP   】波场、BSC、ETH等公链开发的链游GameFi、DIFI、哈希竞猜、足彩投注 等各类DAPP。

🍬【  区块链  】智能合约开发 持币分红、质押分红、Swap、批量空投、靓号生成等系统

🍬【  交易所  】中心化交易所搭建 , 类似火币、币安。使用高性能Java语言开发。

🍬【支付通道】安全加密的支付产品、支持各类行业对接。

🍬【高仿风控】专业的风控防御团队、独创防御方式、自有的风控策略为您的平台保驾护航。

🍬【担保交易】有着多年的担保系统研发经验、otc c2c 、等可定制化担保模式。

🍬【拍卖系统】经过市场运营的稳定拍卖系统、模式可定制。专业的技术维护。

🍬【电报机器人】电报机器人定制服务、例如索引机器人、担保机器人、传话筒机器人、音乐机器人等、独立的机器人技术研发团队，随时为您定制高性能的各类有趣的机器人产品。

🗣
亿贝技术团队非常懂目前市场的困境。对于一线运营成本的损耗，我们将全方位且人性化的降低项目的风险度，欢迎各大团队携高端资源来对接。目前我们的软件服务包含：菲、柬、越、迪、日、韩、国内外众多互联网项目运营团队。为各大团队提供专业的技术服务。

👉
合作流程：
1.确定产品类型版面
2.沟通产品细节和需求文档
3.确定产品后，预付35%定金
4.产品需求开发完成后、预付35%中期款
5.测试完毕，上线之前结算30%尾款
6.维护周期可根据产品运营时间，项目运营收益，周期性结算技术维护费用。

🔥
媒体关注：
GitHub ：  https://github.com/yishellmeta
Twitter :     https://twitter.com/yishellmeta
电报频道  : https://t.me/yishellmeta
电报客服  : https://t.me/pacforever
油管频道  : https://www.youtube.com/channel/UC8ESJQ4-4cQAmZrQ5tBaMzQ
